name: noesis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.0.0
  http:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider:
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/Welcome.png
    - assets/Log in.png
    - assets/Log up.png
    - assets/verb_to_be.png
    - assets/future_perfect.png
    - assets/present_simple.png
    - assets/verb_can.png
    - assets/logo_noesis.png
    - assets/logo_log.png
    - assets/logo_noesis_game.png
    - assets/verbo_to_be_pizarra.png
    - assets/verbo_to_be_tabla.png
    - assets/future_perfect_pizarra.png
    - assets/future_perfect_tabla.png
    - assets/present_simple_pizarra.png
    - assets/present_simple_tabla.png
    - assets/the_verb_can_pizarra.png
    - assets/the_verb_can_tabla.png
    - assets/icon/icon.png
    - assets/audios/She_is_a_doctor.mp3
    - assets/audios/The_sky_is_blue.mp3
    - assets/audios/I_am_happy_today.mp3
    - assets/audios/It_is_raining_outsid.mp3
    - assets/audios/She_will_have_finish.mp3
    - assets/audios/They_will_have_left.mp3
    - assets/audios/I_will_have_studied.mp3
    - assets/audios/We_will_have_arrived.mp3
    - assets/audios/We_watch_TV.mp3
    - assets/audios/She_works_a_lot.mp3
    - assets/audios/He_plays_football.mp3
    - assets/audios/I_study_English.mp3
    - assets/audios/I_can_swim.mp3
    - assets/audios/She_can_dance.mp3
    - assets/audios/We_can_help.mp3
    - assets/audios/They_can_come.mp3

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21